//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradingComapny
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Movement
    {
        public int Product_ID { get; set; }
        public string WHouse_from { get; set; }
        public int Quantity { get; set; }
        public System.DateTime Transfer_Date { get; set; }
        public string WHouse_To { get; set; }
        public System.DateTime Production_Date { get; set; }
    
        public virtual product product { get; set; }
        public virtual WareHouse WareHouse { get; set; }
        public virtual WareHouse WareHouse1 { get; set; }
    }
}
